<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kasus_model extends CI_Model
{

    public $table = 'kasus';
    public $id = 'id_kasus';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kasus', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('tanggal_surat', $q);
	$this->db->or_like('nama_pelapor', $q);
	$this->db->or_like('tanggal_kejadian', $q);
	$this->db->or_like('jlh', $q);
	$this->db->or_like('kg', $q);
	$this->db->or_like('lokasi', $q);
	$this->db->or_like('nama_tersangka', $q);
	$this->db->or_like('tindak_lanjut', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kasus', $q);
	$this->db->or_like('nomor_surat', $q);
	$this->db->or_like('tanggal_surat', $q);
	$this->db->or_like('nama_pelapor', $q);
	$this->db->or_like('tanggal_kejadian', $q);
	$this->db->or_like('jlh', $q);
	$this->db->or_like('kg', $q);
	$this->db->or_like('lokasi', $q);
	$this->db->or_like('nama_tersangka', $q);
	$this->db->or_like('tindak_lanjut', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kasus_model.php */
/* Location: ./application/models/Kasus_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-10 09:06:37 */
/* http://harviacode.com */